services:
   tracker.issue.lifecycle.event_listener:
      class: Tracker\ActivitiesBundle\EventListener\IssueEventListener
      tags:
      - { name: doctrine.event_listener, event: preUpdate }
#     - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }