<?php

namespace Tracker\ActivitiesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Tracker\UserBundle\Entity\User;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return array
     */
    public function findAvailableForUser(User $user)
    {
        $qb = $this->createQueryBuilder('activity');

        $query = $qb
            ->leftJoin('activity.project', 'p')
            ->leftJoin('p.members', 'm')
            ->where('m.id = :user_id')
            ->setParameter('user_id', $user->getId())
            ->setMaxResults(10)
            ->getQuery();

        return $query->getResult();
    }
}
