services:
    acme_user.registration.form.type:
        class: Tracker\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }

    tracker.user.security.voter:
        class:      Tracker\UserBundle\Security\Authorization\Voter\UserVoter
        public:     false
        tags:
            - { name: security.voter }

    tracker.registration.form.type:
        class: Tracker\UserBundle\Form\UserType
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: tracker_userBundle_user }