services:
    tracker.project.security.voter:
        class:      Tracker\ProjectBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
            - { name: security.voter }

    tracker.project.lifecycle.event_listener:
        class: Tracker\ProjectBundle\EventListener\ProjectEventListener
        arguments:
        tags:
            - { name: doctrine.event_listener, event: postPersist }