services:
    tracker.project.security.voter:
        class:      Tracker\ProjectBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
           - { name: security.voter }