<?php

namespace Tracker\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Tracker\UserBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return array
     */
    public function findByCollaborator(User $user)
    {
        $query = $this->createQueryBuilder('project');

        if (!$user->hasRole(User::ROLE_ADMIN) && !$user->hasRole(User::ROLE_MANAGER)) {
            $query->leftJoin('project.members', 'members')
                ->where('members.id = :member_id')
                ->setParameter('member_id', $user->getId());
        }

        return $query->getQuery()->getResult();
    }
}
