<?php

namespace Tracker\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findOneByCode($code)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.code = :code')
            ->setParameter('code', $code);

        return $qb->getQuery()->getSingleResult();
    }
}
