services:
    tracker.issue.security.voter:
        class:      Tracker\IssueBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
           - { name: security.voter }
    tracker.issueComment.security.voter:
        class:      Tracker\IssueBundle\Security\Authorization\Voter\CommentVoter
        public:     false
        tags:
            - { name: security.voter }