services:
    tracker.issue.security.voter:
        class:      Tracker\IssueBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
           - { name: security.voter }

    tracker.issueComment.security.voter:
        class:      Tracker\IssueBundle\Security\Authorization\Voter\CommentVoter
        public:     false
        tags:
            - { name: security.voter }

    tracker_issueBundle_issue:
        class: Tracker\IssueBundle\Form\IssueType
        arguments:
            - @security.token_storage
        tags:
            - { name: form.type, alias: tracker_issueBundle_issue }

    tracker_issueBundle_issueSubTask_form:
        class: Tracker\IssueBundle\Form\IssueSubTaskType
        arguments:
            - @security.token_storage
        tags:
            - { name: form.type, alias: tracker_issueBundle_issueSubTask_form }

    tracker_issueBundle_comment_form:
        class: Tracker\IssueBundle\Form\IssueCommentType
        arguments:
          - @security.token_storage
        tags:
          - { name: form.type, alias: tracker_issueBundle_comment_form }
